[package]
name = "pi_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
